import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    const examples = {
        defaultUrl: "https://fivethirtyeight.datasettes.com/fivethirtyeight/nba-elo~2Fnbaallelo.json",
        gamePtsTeamId: "/?url=https%3A%2F%2Ffivethirtyeight.datasettes.com%2Ffivethirtyeight%2Fnba-elo~2Fnbaallelo.json#g.mark=bar&g.x_column=game_id&g.x_type=ordinal&g.y_column=pts&g.y_type=quantitative&g.color_column=team_id",
        ptsResult: "/?url=https%3A%2F%2Ffivethirtyeight.datasettes.com%2Ffivethirtyeight%2Fnba-elo%7E2Fnbaallelo.json#g.mark=circle&g.x_column=opp_pts&g.x_type=quantitative&g.y_column=pts&g.y_type=quantitative&g.color_column=game_result&g.size_column=opp_pts",
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Datasette Vega</h1>
                <p>Enter the URL of the JSON version of any Datasette table:</p>
                <form action="." method="GET" style={{ marginBottom: "2em", }}>
                    <input id="jsonUrl" type="text" name="url" value={examples.defaultUrl} style={{ width: "80%", fontSize: "1.2em", }} />
                    <input type="submit" value="Load" style={{ fontSize: "1.2em", border: "1px solid #ccc", }} />
                    <p>
                        Examples:
                        <a href={examples.gamePtsTeamId}>game_id/pts/team_id</a>,
                        <a href={examples.ptsResult}>pts/opp_pts/result</a>
                    </p>
                </form>
                <div id="vis-tool"></div>
                <div id="vis-wrapper" style={{ overflow: "auto" }}>
                    <div id="vis"></div>
                </div>
            </main>
        </div>
    )
}
